#![allow(unused_imports, unused_attributes, clippy::all, rustdoc::all)]
//! This module contains the sol! generated bindings for solidity contracts.
//! This is autogenerated code.
//! Do not manually edit these files.
//! These files may be overwritten by the codegen system at any time.
pub mod i_blueprint_service_manager;
pub mod i_master_blueprint_service_manager;
pub mod i_multi_asset_delegation;
pub mod i_tangle;
pub mod i_tangle_admin;
pub mod i_tangle_full;
pub mod i_tangle_blueprints;
pub mod i_tangle_governance;
pub mod i_tangle_token;
pub mod i_tangle_jobs;
pub mod i_tangle_operators;
pub mod i_tangle_payments_internal;
pub mod i_tangle_rewards;
pub mod i_tangle_security_view;
pub mod i_tangle_services;
pub mod i_tangle_slashing;
pub mod multi_asset_delegation;
pub mod i_operator_status_registry;
pub mod operator_status_registry;
