[package]
name = "tnt-core-bytecode"
version = "0.3.0"
edition = "2021"
description = "Bytecode exports for TNT Core Solidity contracts"
license = "MIT"

[features]
default = ["build-script"]
build-script = []

[build-dependencies]
serde_json = "1.0"
