// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

import { Script, console2 } from "forge-std/Script.sol";
import { ShieldedGateway } from "../src/shielded/ShieldedGateway.sol";
import { ShieldedCredits } from "../src/shielded/ShieldedCredits.sol";

/// @title DeployShielded
/// @notice Deploys the ShieldedGateway and registers VAnchor pools.
///
/// @dev Prerequisites (deployed separately via protocol-solidity tooling):
///      1. Poseidon hasher libraries (T2-T6) — bytecode generated by circomlibjs
///      2. PoseidonHasher contract — links to Poseidon libraries
///      3. Verifier contracts (Verifier2_2, Verifier8_2, etc.) — circuit-specific
///      4. VAnchorVerifier — routes to correct verifier by edge count / input count
///      5. FungibleTokenWrapper — wraps stablecoins into a single pool token
///      6. VAnchorTree — the shielded pool itself
///      7. SignatureBridge + AnchorHandler — for cross-chain root relays
///
///      These contracts come from the audited protocol-solidity codebase and should
///      be deployed using their existing TypeScript deployment tooling to ensure
///      correct Poseidon bytecode generation and verifier linking.
///
///      This script ONLY deploys the ShieldedGateway (the new glue contract)
///      and registers the already-deployed pools.
///
/// Usage:
///   TANGLE=0x... GATEWAY_OWNER=0x... POOLS="token1:pool1,token2:pool2" \
///   forge script script/DeployShielded.s.sol:DeployShielded --rpc-url $RPC_URL --broadcast
contract DeployShielded is Script {
    function run() external {
        address tangleAddr = vm.envAddress("TANGLE");
        address gatewayOwner = vm.envAddress("GATEWAY_OWNER");

        vm.startBroadcast();

        // Deploy credits contract
        ShieldedCredits creditsContract = new ShieldedCredits();
        console2.log("ShieldedCredits deployed at:", address(creditsContract));

        // Deploy the gateway
        ShieldedGateway gateway = new ShieldedGateway(tangleAddr, address(creditsContract), gatewayOwner);
        console2.log("ShieldedGateway deployed at:", address(gateway));

        // Register pools from env var: "wrappedToken1:pool1,wrappedToken2:pool2"
        string memory poolsEnv = vm.envOr("POOLS", string(""));
        if (bytes(poolsEnv).length > 0) {
            _registerPools(gateway, poolsEnv);
        }

        vm.stopBroadcast();
    }

    function _registerPools(ShieldedGateway gateway, string memory poolsStr) internal {
        // Parse comma-separated "token:pool" pairs
        // Foundry doesn't have great string splitting, so we parse manually
        bytes memory poolsBytes = bytes(poolsStr);
        uint256 start = 0;

        for (uint256 i = 0; i <= poolsBytes.length; i++) {
            if (i == poolsBytes.length || poolsBytes[i] == ",") {
                if (i > start) {
                    // Extract "token:pool" substring
                    bytes memory pair = new bytes(i - start);
                    for (uint256 j = start; j < i; j++) {
                        pair[j - start] = poolsBytes[j];
                    }
                    _registerPair(gateway, pair);
                }
                start = i + 1;
            }
        }
    }

    function _registerPair(ShieldedGateway gateway, bytes memory pair) internal {
        // Find the ":" separator
        for (uint256 i = 0; i < pair.length; i++) {
            if (pair[i] == ":") {
                // Extract token and pool addresses
                bytes memory tokenHex = new bytes(i);
                bytes memory poolHex = new bytes(pair.length - i - 1);

                for (uint256 j = 0; j < i; j++) {
                    tokenHex[j] = pair[j];
                }
                for (uint256 j = i + 1; j < pair.length; j++) {
                    poolHex[j - i - 1] = pair[j];
                }

                address token = vm.parseAddress(string(tokenHex));
                address pool = vm.parseAddress(string(poolHex));

                gateway.registerPool(token, pool);
                console2.log("Registered pool:", token, "=>", pool);
                return;
            }
        }
    }
}
