#![allow(missing_docs, clippy::all, rustdoc::all)]

/// Autogenerated alloy bindings emitted by `forge bind`.
pub mod bindings;

pub use bindings::r#i_blueprint_service_manager::IBlueprintServiceManager;
pub use bindings::r#i_operator_status_registry::IOperatorStatusRegistry;
pub use bindings::r#i_tangle::ITangle;
pub use bindings::r#i_tangle_admin::ITangleAdmin;
pub use bindings::r#i_tangle_blueprints::ITangleBlueprints;
pub use bindings::r#i_tangle_full::ITangleFull;
pub use bindings::r#i_tangle_governance::ITangleGovernance;
pub use bindings::r#i_tangle_jobs::ITangleJobs;
pub use bindings::r#i_tangle_operators::ITangleOperators;
pub use bindings::r#i_tangle_rewards::ITangleRewards;
pub use bindings::r#i_tangle_services::ITangleServices;
pub use bindings::r#i_tangle_slashing::ITangleSlashing;
pub use bindings::r#i_tangle_token::ITangleToken;
pub use bindings::r#multi_asset_delegation::MultiAssetDelegation;
pub use bindings::r#multi_asset_delegation::MultiAssetDelegation as IMultiAssetDelegation;

/// Git commit that was used to generate the bindings.
pub const TNT_CORE_VERSION: &str = include_str!("../TNT_CORE_VERSION");

/// Flattened contract ABIs that downstream tooling can consume.
pub mod abi {
    pub const ITANGLE: &str = include_str!("../abi/ITangle.json");
    pub const IBLUEPRINT_SERVICE_MANAGER: &str =
        include_str!("../abi/IBlueprintServiceManager.json");
    pub const IOPERATOR_STATUS_REGISTRY: &str = include_str!("../abi/IOperatorStatusRegistry.json");
    pub const MULTI_ASSET_DELEGATION: &str = include_str!("../abi/MultiAssetDelegation.json");
}
