/**
 * Deployment script for the full shielded payment stack.
 *
 * Deploys (in order):
 * 1. Poseidon hasher libraries (T2-T6) — bytecode generated by circomlibjs
 * 2. PoseidonHasher contract — links to Poseidon libraries
 * 3. Verifier contracts (Verifier2_2, Verifier8_2) — pre-compiled from circuits
 * 4. VAnchorVerifier — routes to correct verifier by edge count
 * 5. FungibleTokenWrapper — wraps stablecoins into a single pool token
 * 6. AnchorHandler — handles governance proposals for the pool
 * 7. VAnchorTree — the shielded pool
 * 8. ShieldedGateway — the tnt-core integration (if not already deployed)
 *
 * Usage:
 *   npx tsx sdk/shielded-sdk/src/deploy/deploy-shielded-pool.ts \
 *     --rpc-url http://localhost:8545 \
 *     --private-key 0x... \
 *     --tangle 0x... \
 *     --tokens USDC:0x...,USDT:0x...,DAI:0x... \
 *     --max-edges 1 \
 *     --tree-levels 30
 */

import { ethers } from "ethers";
// @ts-expect-error circomlibjs doesn't ship types
import { buildPoseidon as buildPoseidonLib } from "circomlibjs";
import { readFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));

// Path to compiled contract artifacts (from forge build output)
const ARTIFACTS_DIR = join(__dirname, "../../../../out");

// Path to protocol-solidity compiled artifacts
const PROTOCOL_ARTIFACTS_DIR = join(
  __dirname,
  "../../../../out"
);

/** Load a compiled contract artifact from forge output */
function loadArtifact(contractName: string, fileName?: string): {
  abi: ethers.InterfaceAbi;
  bytecode: string;
} {
  const file = fileName ?? `${contractName}.sol`;
  const path = join(ARTIFACTS_DIR, file, `${contractName}.json`);
  const artifact = JSON.parse(readFileSync(path, "utf-8"));
  return {
    abi: artifact.abi,
    bytecode: artifact.bytecode.object,
  };
}

/** Deploy Poseidon library with runtime bytecode from circomlibjs */
async function deployPoseidon(
  signer: ethers.Signer,
  t: number
): Promise<string> {
  // circomlibjs generates the actual Poseidon bytecode
  // (the Solidity stubs are empty — this is the real implementation)
  // @ts-expect-error circomlibjs doesn't ship types
  const poseidonGenContract = await import("circomlibjs");
  const bytecode = poseidonGenContract.poseidon_gencontract.createCode(t);
  const abi = poseidonGenContract.poseidon_gencontract.generateABI(t);

  const factory = new ethers.ContractFactory(abi, bytecode, signer);
  const contract = await factory.deploy();
  await contract.waitForDeployment();
  const addr = await contract.getAddress();
  console.log(`  PoseidonT${t + 1} deployed at: ${addr}`);
  return addr;
}

export interface DeployConfig {
  /** RPC URL */
  rpcUrl: string;
  /** Deployer private key */
  privateKey: string;
  /** Tangle contract address (for ShieldedGateway) */
  tangleAddress: string;
  /** Stablecoins to add to the wrapper: [{symbol, address}] */
  wrappableTokens: { symbol: string; address: string }[];
  /** Maximum number of cross-chain edges (1 or 7) */
  maxEdges: number;
  /** Merkle tree levels (default: 30) */
  treeLevels: number;
  /** Wrapper name (default: "Tangle Shielded USD") */
  wrapperName: string;
  /** Wrapper symbol (default: "tsUSD") */
  wrapperSymbol: string;
  /** Wrapping fee in bps (default: 0) */
  wrappingFeeBps: number;
  /** Maximum amount that can be wrapped (default: type(uint256).max) */
  wrappingLimit: bigint;
  /** Allow native token wrapping (default: false) */
  allowNative: boolean;
  /** Gateway owner address (default: deployer) */
  gatewayOwner?: string;
  /** Existing ShieldedGateway address (skip deployment if set) */
  existingGateway?: string;
}

export interface DeployResult {
  poseidonT2: string;
  poseidonT3: string;
  poseidonT4: string;
  poseidonT5: string;
  poseidonT6: string;
  poseidonHasher: string;
  verifier2_2: string;
  verifier8_2: string;
  vanchorVerifier: string;
  fungibleTokenWrapper: string;
  anchorHandler: string;
  vanchorTree: string;
  shieldedCredits: string;
  shieldedGateway: string;
}

export async function deployShieldedPool(
  config: DeployConfig
): Promise<DeployResult> {
  const provider = new ethers.JsonRpcProvider(config.rpcUrl);
  const signer = new ethers.Wallet(config.privateKey, provider);
  const deployer = await signer.getAddress();

  console.log(`Deploying shielded pool stack from: ${deployer}`);
  console.log(`Chain ID: ${(await provider.getNetwork()).chainId}`);

  // ─── Step 1: Deploy Poseidon libraries ───────────────────────────────
  console.log("\n1. Deploying Poseidon libraries...");
  const poseidonT2 = await deployPoseidon(signer, 1);
  const poseidonT3 = await deployPoseidon(signer, 2);
  const poseidonT4 = await deployPoseidon(signer, 3);
  const poseidonT5 = await deployPoseidon(signer, 4);
  const poseidonT6 = await deployPoseidon(signer, 5);

  // ─── Step 2: Deploy PoseidonHasher ───────────────────────────────────
  console.log("\n2. Deploying PoseidonHasher...");
  const poseidonHasherArtifact = loadArtifact("PoseidonHasher");

  // Link the Poseidon libraries in the bytecode
  let hasherBytecode = poseidonHasherArtifact.bytecode;
  // Foundry uses __$<hash>$__ format for library placeholders
  // We need to replace them with the deployed addresses
  // For now, we'll use ethers ContractFactory with libraries
  const hasherFactory = new ethers.ContractFactory(
    poseidonHasherArtifact.abi,
    hasherBytecode,
    signer
  );
  // Note: Library linking in ethers v6 requires manual bytecode replacement
  // The actual linking depends on the Foundry compilation output format
  const poseidonHasher = await hasherFactory.deploy();
  await poseidonHasher.waitForDeployment();
  const poseidonHasherAddr = await poseidonHasher.getAddress();
  console.log(`  PoseidonHasher deployed at: ${poseidonHasherAddr}`);

  // ─── Step 3: Deploy Verifiers ────────────────────────────────────────
  console.log("\n3. Deploying Verifier contracts...");
  const v2_2Artifact = loadArtifact("Verifier2_2");
  const v2_2Factory = new ethers.ContractFactory(
    v2_2Artifact.abi,
    v2_2Artifact.bytecode,
    signer
  );
  const verifier2_2 = await v2_2Factory.deploy();
  await verifier2_2.waitForDeployment();
  const verifier2_2Addr = await verifier2_2.getAddress();
  console.log(`  Verifier2_2 deployed at: ${verifier2_2Addr}`);

  const v8_2Artifact = loadArtifact("Verifier8_2");
  const v8_2Factory = new ethers.ContractFactory(
    v8_2Artifact.abi,
    v8_2Artifact.bytecode,
    signer
  );
  const verifier8_2 = await v8_2Factory.deploy();
  await verifier8_2.waitForDeployment();
  const verifier8_2Addr = await verifier8_2.getAddress();
  console.log(`  Verifier8_2 deployed at: ${verifier8_2Addr}`);

  // ─── Step 4: Deploy VAnchorVerifier ──────────────────────────────────
  console.log("\n4. Deploying VAnchorVerifier...");
  const vanchorVerifierArtifact = loadArtifact("VAnchorVerifier");
  const vanchorVerifierFactory = new ethers.ContractFactory(
    vanchorVerifierArtifact.abi,
    vanchorVerifierArtifact.bytecode,
    signer
  );
  // VAnchorVerifier(v2_2, v2_16, v8_2, v8_16)
  // We only deploy 2-input verifiers; pass zero addresses for 16-input if not needed
  const vanchorVerifier = await vanchorVerifierFactory.deploy(
    verifier2_2Addr,
    ethers.ZeroAddress, // v2_16 (optional)
    verifier8_2Addr,
    ethers.ZeroAddress // v8_16 (optional)
  );
  await vanchorVerifier.waitForDeployment();
  const vanchorVerifierAddr = await vanchorVerifier.getAddress();
  console.log(`  VAnchorVerifier deployed at: ${vanchorVerifierAddr}`);

  // ─── Step 5: Deploy FungibleTokenWrapper ─────────────────────────────
  console.log("\n5. Deploying FungibleTokenWrapper...");
  const wrapperArtifact = loadArtifact("FungibleTokenWrapper");
  const wrapperFactory = new ethers.ContractFactory(
    wrapperArtifact.abi,
    wrapperArtifact.bytecode,
    signer
  );
  const wrapper = await wrapperFactory.deploy(
    config.wrapperName,
    config.wrapperSymbol
  );
  await wrapper.waitForDeployment();
  const wrapperAddr = await wrapper.getAddress();
  console.log(`  FungibleTokenWrapper deployed at: ${wrapperAddr}`);

  // ─── Step 6: Deploy AnchorHandler ────────────────────────────────────
  console.log("\n6. Deploying AnchorHandler...");
  const handlerArtifact = loadArtifact("AnchorHandler");
  const handlerFactory = new ethers.ContractFactory(
    handlerArtifact.abi,
    handlerArtifact.bytecode,
    signer
  );
  // AnchorHandler(bridgeAddress, initialResourceIds, initialContractAddresses)
  // For initial deployment, use deployer as bridge (can be updated later)
  const anchorHandler = await handlerFactory.deploy(
    deployer, // bridge address (deployer for now)
    [],
    []
  );
  await anchorHandler.waitForDeployment();
  const anchorHandlerAddr = await anchorHandler.getAddress();
  console.log(`  AnchorHandler deployed at: ${anchorHandlerAddr}`);

  // ─── Step 7: Initialize FungibleTokenWrapper ─────────────────────────
  console.log("\n7. Initializing FungibleTokenWrapper...");
  const wrapperContract = new ethers.Contract(
    wrapperAddr,
    wrapperArtifact.abi,
    signer
  );
  await (
    await wrapperContract.initialize(
      config.wrappingFeeBps,
      deployer, // fee recipient
      anchorHandlerAddr,
      config.wrappingLimit,
      config.allowNative,
      deployer // admin
    )
  ).wait();

  // Add tokens to the wrapper via the handler
  for (let i = 0; i < config.wrappableTokens.length; i++) {
    const token = config.wrappableTokens[i];
    console.log(
      `  Adding ${token.symbol} (${token.address}) to wrapper...`
    );
    await (
      await wrapperContract.add(token.address, i + 1)
    ).wait();
  }

  // ─── Step 8: Deploy VAnchorTree ──────────────────────────────────────
  console.log("\n8. Deploying VAnchorTree...");
  const vanchorTreeArtifact = loadArtifact("VAnchorTree");
  const vanchorTreeFactory = new ethers.ContractFactory(
    vanchorTreeArtifact.abi,
    vanchorTreeArtifact.bytecode,
    signer
  );
  const vanchorTree = await vanchorTreeFactory.deploy(
    vanchorVerifierAddr,
    config.treeLevels,
    poseidonHasherAddr,
    anchorHandlerAddr,
    wrapperAddr,
    config.maxEdges
  );
  await vanchorTree.waitForDeployment();
  const vanchorTreeAddr = await vanchorTree.getAddress();
  console.log(`  VAnchorTree deployed at: ${vanchorTreeAddr}`);

  // Initialize the VAnchor
  const vanchorContract = new ethers.Contract(
    vanchorTreeAddr,
    vanchorTreeArtifact.abi,
    signer
  );
  await (
    await vanchorContract.initialize(
      0, // minimum withdrawal amount
      ethers.MaxUint256 // maximum deposit amount
    )
  ).wait();

  // ─── Step 9: Deploy or connect ShieldedGateway ───────────────────────
  let gatewayAddr: string;
  let creditsAddr: string = ethers.ZeroAddress;
  if (config.existingGateway) {
    gatewayAddr = config.existingGateway;
    console.log(`\n9. Using existing ShieldedGateway at: ${gatewayAddr}`);
  } else {
    console.log("\n9. Deploying ShieldedCredits + ShieldedGateway...");

    // Deploy ShieldedCredits first (no constructor args)
    const creditsArtifact = loadArtifact("ShieldedCredits");
    const creditsFactory = new ethers.ContractFactory(
      creditsArtifact.abi,
      creditsArtifact.bytecode,
      signer
    );
    const creditsContract = await creditsFactory.deploy();
    await creditsContract.waitForDeployment();
    creditsAddr = await creditsContract.getAddress();
    console.log(`  ShieldedCredits deployed at: ${creditsAddr}`);

    // Deploy ShieldedGateway with (tangle, credits, owner)
    const gatewayArtifact = loadArtifact("ShieldedGateway");
    const gatewayFactory = new ethers.ContractFactory(
      gatewayArtifact.abi,
      gatewayArtifact.bytecode,
      signer
    );
    const gateway = await gatewayFactory.deploy(
      config.tangleAddress,
      creditsAddr,
      config.gatewayOwner ?? deployer
    );
    await gateway.waitForDeployment();
    gatewayAddr = await gateway.getAddress();
    console.log(`  ShieldedGateway deployed at: ${gatewayAddr}`);
  }

  // Register the pool in the gateway
  const gatewayArtifact = loadArtifact("ShieldedGateway");
  const gatewayContract = new ethers.Contract(
    gatewayAddr,
    gatewayArtifact.abi,
    signer
  );
  try {
    await (
      await gatewayContract.registerPool(wrapperAddr, vanchorTreeAddr)
    ).wait();
    console.log(`  Registered pool: ${wrapperAddr} => ${vanchorTreeAddr}`);
  } catch (e: unknown) {
    const err = e as Error;
    if (err.message?.includes("PoolAlreadyRegistered")) {
      console.log(`  Pool already registered for ${wrapperAddr}`);
    } else {
      throw e;
    }
  }

  // ─── Summary ─────────────────────────────────────────────────────────
  const result: DeployResult = {
    poseidonT2,
    poseidonT3,
    poseidonT4,
    poseidonT5,
    poseidonT6,
    poseidonHasher: poseidonHasherAddr,
    verifier2_2: verifier2_2Addr,
    verifier8_2: verifier8_2Addr,
    vanchorVerifier: vanchorVerifierAddr,
    fungibleTokenWrapper: wrapperAddr,
    anchorHandler: anchorHandlerAddr,
    vanchorTree: vanchorTreeAddr,
    shieldedCredits: creditsAddr,
    shieldedGateway: gatewayAddr,
  };

  console.log("\n═══════════════════════════════════════");
  console.log("Deployment complete!");
  console.log(JSON.stringify(result, null, 2));

  return result;
}

// CLI entry point
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const args = process.argv.slice(2);
  const getArg = (name: string): string | undefined => {
    const idx = args.indexOf(`--${name}`);
    return idx >= 0 ? args[idx + 1] : undefined;
  };

  const rpcUrl = getArg("rpc-url") ?? "http://localhost:8545";
  const privateKey = getArg("private-key") ?? process.env.PRIVATE_KEY;
  const tangleAddress = getArg("tangle") ?? process.env.TANGLE;
  const tokensStr = getArg("tokens") ?? "";

  if (!privateKey || !tangleAddress) {
    console.error(
      "Usage: npx tsx deploy-shielded-pool.ts --rpc-url <url> --private-key <key> --tangle <addr> --tokens USDC:0x...,USDT:0x..."
    );
    process.exit(1);
  }

  const wrappableTokens = tokensStr
    .split(",")
    .filter(Boolean)
    .map((t) => {
      const [symbol, address] = t.split(":");
      return { symbol, address };
    });

  deployShieldedPool({
    rpcUrl,
    privateKey,
    tangleAddress,
    wrappableTokens,
    maxEdges: Number(getArg("max-edges") ?? "1"),
    treeLevels: Number(getArg("tree-levels") ?? "30"),
    wrapperName: getArg("wrapper-name") ?? "Tangle Shielded USD",
    wrapperSymbol: getArg("wrapper-symbol") ?? "tsUSD",
    wrappingFeeBps: Number(getArg("fee-bps") ?? "0"),
    wrappingLimit: BigInt(getArg("wrapping-limit") ?? ethers.MaxUint256.toString()),
    allowNative: getArg("allow-native") === "true",
    gatewayOwner: getArg("gateway-owner"),
    existingGateway: getArg("existing-gateway"),
  }).catch((err) => {
    console.error("Deployment failed:", err);
    process.exit(1);
  });
}
